pipeline {

    agent any

    environment {
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run DQ Tests') {
            steps {

                sh '''
                pytest tests -m "parquet_data" \
                    --db_host="postgres" \
                    --db_port="5432" \
                    --db_name="mydatabase" \
                    --db_user=$POSTGRES_SECRET_USR \
                    --db_password=$POSTGRES_SECRET_PSW \
                    --html=html_report/report.html \
                    --self-contained-html
                '''
            }
        }

        stage('Archive Report') {
            steps {

                archiveArtifacts artifacts: 'html_report/**'

                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'html_report',
                    reportFiles: 'report.html',
                    reportName: 'PyTest DQ Report'
                ])
            }
        }
    }
}
